import os

BASE_DIR = os.getcwd()
DATASETS = {
    "imdb": {
        "files": {"all": "Datasets/IMDB/IMDB_Dataset.csv"},
        "format": "csv",
        "rename": {"review": "text", "sentiment": "label"},
        "need_label_encoding": True,
        "splits": [("train", 0.64), ("val", 0.16), ("test", 0.20)],
    },
    "sst2": {
        "files": {
            "train": "datasets/SST-2/train.jsonl",
            "val": "datasets/SST-2/dev.jsonl",
            "test": "datasets/SST-2/test.jsonl",
        },
        "format": "jsonl",
        "text_col": "text",
        "label_col": "label",
        "need_label_encoding": False,
        "num_labels": 2,
    },
    "sst5": {
        "files": {
            "train": "datasets/SST-5/train.jsonl",
            "val": "datasets/SST-5/dev.jsonl",
            "test": "datasets/SST-5/test.jsonl",
        },
        "format": "jsonl",
        "text_col": "text",
        "label_col": "label",
        "need_label_encoding": False,
        "num_labels": 5,
    },
    "mr": {
        "files": {
            "train": "datasets/MR/train.parquet",
            "val": "datasets/MR/validation.parquet",
            "test": "datasets/MR/test.parquet",
        },
        "format": "parquet",
        "text_col": "text",
        "label_col": "label",
        "need_label_encoding": False,
        "num_labels": 2,
    },
    "ng20": {
        "files": {
            "train": "datasets/NG20/20ng-train-all-terms.txt",
            "test": "datasets/NG20/20ng-test-all-terms.txt",
        },
        "format": "txt",
        "text_col": "text",
        "label_col": "label",
        "splits": [("train", 0.8), ("val", 0.2)],
        "need_label_encoding": True,
        "num_labels": 20,
    },
    "snips": {
        "files": {
            "train": "datasets/snips/snips_train.parquet",
            "test": "datasets/snips/snips_test.parquet",
        },
        "format": "parquet",
        "text_col": "utterance",
        "label_col": "label",
        "splits": [("train", 0.8), ("val", 0.2)],
        "need_label_encoding": False,
        "num_labels": 7,
    },
    "subj": {
        "files": {
            "train": "datasets/SUBJ/train.jsonl",
            "test": "datasets/SUBJ/test.jsonl",
        },
        "format": "jsonl",
        "text_col": "text",
        "label_col": "label",
        "splits": [("train", 0.8), ("val", 0.2)],
        "need_label_encoding": False,
        "num_labels": 2,
    },
    "trec6": {
        "files": {
            "train": "datasets/TREC/train.csv",
            "test": "datasets/TREC/test.csv",
        },
        "format": "csv",
        "text_col": "text",
        "label_col": "label-coarse",
        "splits": [("train", 0.8), ("val", 0.2)],
        "need_label_encoding": False,
        "num_labels": 6,
    },
    "trec47": {
        "files": {
            "train": "datasets/TREC/train.csv",
            "test": "datasets/TREC/test.csv",
        },
        "format": "csv",
        "text_col": "text",
        "label_col": "label-fine",
        "splits": [("train", 0.8), ("val", 0.2)],
        "need_label_encoding": False,
        "num_labels": 47,
    },
    "agnews": {
        "files": {
            "train": "datasets/Agnews/train.csv",
            "test": "datasets/Agnews/test.csv",
        },
        "format": "csv",
        "text_col": "Title",
        "label_col": "Class Index",
        "splits": [("train", 0.8), ("val", 0.2)],
        "need_label_encoding": True,
        "num_labels": 4,
    },
    "r8": {
        "files": {
            "train": "datasets/R8/r8-train-all-terms.txt",
            "test": "datasets/R8/r8-test-all-terms.txt",
        },
        "format": "txt",
        "text_col": "text",
        "label_col": "label",
        "splits": [("train", 0.8), ("val", 0.2)],
        "need_label_encoding": True,
        "num_labels": 8,
    },
    "ohsumed": {
        "files": {
            "train": "datasets/Ohsumed/train.csv",
            "val": "datasets/Ohsumed/val.csv",
            "test": "datasets/Ohsumed/test.csv",
        },
        "format": "csv",
        "text_col": "text",
        "label_col": "label",
        "need_label_encoding": False,
        "num_labels": 23,
    },
    "emoji": {
        "files": {
            "train": "datasets/twitter_emoji/train_emoji.parquet",
            "val": "datasets/twitter_emoji/validation_emoji.parquet",
            "test": "datasets/twitter_emoji/test_emoji.parquet",
        },
        "format": "parquet",
        "text_col": "text",
        "label_col": "label",
        "need_label_encoding": False,
        "num_labels": 20,
    },
    "emotion": {
        "files": {
            "train": "datasets/twitter_emotion/train_emotion.parquet",
            "val": "datasets/twitter_emotion/validation_emotion.parquet",
            "test": "datasets/twitter_emotion/test_emotion.parquet",
        },
        "format": "parquet",
        "text_col": "text",
        "label_col": "label",
        "need_label_encoding": False,
        "num_labels": 4,
    },
    "review": {
        "files": {
            "train": "datasets/CourseraReview/train.csv",
            "val": "datasets/CourseraReview/val.csv",
            "test": "datasets/CourseraReview/test.csv",
        },
        "format": "csv",
        "text_col": "text",
        "label_col": "label",
        "need_label_encoding": True,
        "num_labels": 5,
    },
}
